Feature/linkedin api updates 2023
fivetran/dbt_linkedin pull request #28
Opened 2023-02-06 18:56 UTC by fivetran-sheringuyen

**Are you a current Fivetran customer?** 

Fivetran employee 💃 

**What change(s) does this PR introduce?** 

## 🚨 Breaking Changes 🚨
Due to Linkedin Ads API [change in January 2023](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/recent-changes?view=li-lms-2022-12#january-2023), there have been updates in the Linkedin Ads Fivetran Connector and therefore, updates to this Linkedin package. 

The following fields have been completely deprecated in the `stg_linkedin_ads__creative_history` model:
- `type`
- `call_to_action_label_type`
- `version_tag`

## Updates
- `linkedin_ads__creative_report` now includes `campaign.type as campaign_type` as a proxy for the previously used `creative.type` field.
- `linkedin_ads__creative_report` no longer includes the fields `creative.version_tag`, `creative.type` and `creative.call_to_action_label_type`.
- `linkedin_ads__creative_report` now leverages `report.creative_id` instead of `creative.creative_id`. 
- `linkedin_ads__url_report` no longer includes the field `creative.version_tag`.

## Under the hood
For more information, please refer to [PR #](REFERENCE SOURCE PACKAGE PR)
Legacy fields have been updated respectively in the connector and `dbt_linkedin_source v0.7.0` includes modifications that could affect the below fields within the `linkedin_ads__creative_history` model:
- `last_modified_at`
- `created_at`
- `status`

For more information, please refer to [PR #](REFERENCE SOURCE PACKAGE PR)

**Did you update the CHANGELOG?** 

- [x] Yes

**Does this PR introduce a breaking change?**

- [x] Yes (please provide breaking change details below.)
- [ ] No  (please provide an explanation as to how the change is non-breaking below.)

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [x] Yes

**Is this PR in response to a previously created Bug or Feature Request**

- [ ] Yes, Issue/Feature [link bug/feature number here]
- [x] No 

**How did you test the PR changes?** 

 

- [x] Buildkite  
- [x] Local (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 

- [x] BigQuery
- [x] Redshift
- [x] Snowflake
- [x] Postgres
- [x] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

2023-02-06 21:03 UTC, fivetran-sheringuyen commented
To-do:
- [ ] Docs to be generated before merge & release!

2023-02-07 16:30 UTC, fivetran-joemarkiewicz requested changes
@fivetran-sheringuyen The changes look good; however, I will hold off on approving until we get confirmation from the product team that these are good to roll out.

Additionally, I had a few super minor comments to address in the meantime.

2023-02-07 16:30 UTC, fivetran-joemarkiewicz commented on packages.yml
> +#   version: [">=0.7.0", "<0.8.0"]
We should also update the README to reference this new version range of the source package.

2023-02-07 19:08 UTC, fivetran-sheringuyen commented on integration_tests/dbt_project.yml
> +version: '0.7.0'
Good catch! Updated both parts of the README!

2023-03-03 23:39 UTC, Csgoodman approved these changes
Looks good to me! Very thorough change log :)

2023-03-06 15:47 UTC, fivetran-joemarkiewicz approved these changes
These changes look good to me! Thanks again @fivetran-sheringuyen

2023-03-06 15:47 UTC, fivetran-joemarkiewicz commented on packages.yml
> +#   version: [">=0.7.0", "<0.8.0"]
Reminder to update before merge

2023-03-23 20:26 UTC, merged